### ISSUE TITLE
Can't Submit or Cancel

### ISSUE THREAD

**Issue by Flobbah** [CherryozZ/qb-menu-dialog#1]
Hi,
when trying to submit or cancel when in dialog it wont let me do that.
Got errors in console:
https://i.gyazo.com/7a3c3765ff94d6eb133d864fd09ddb4d.png
https://i.gyazo.com/bc9e6ff1fbe6d612fe55fa0b9b412a79.png

**Comment by Flobbah** [comment]
Wow, i found it... I am just stupid... in ui.html there is this code
`<script src="nui://qb-core/html/js/wrapper.js"></script>`
it should be like this: `<script src="nui://qb-core/html/wrapper.js"></script>`

**Comment by ccheerry** [comment]
My bad, atm i uploaded this the qb-core "rework" hasnt happened, which deleted the js subfolder, im changing it so it goes with the latest QBCore versions
